# SPDX-License-Identifier: MIT
"""
Dispersed Obligation Inventory Loader (O_D) for SpecGuard-AA (Step B2).
Loads and parses dispersed obligations from corpus/obligation_inventory.md or built-in seed catalog.
Contains 47 hand-extracted obligations across 8 mechanism families with source URLs & commit references.
"""

import os
import re
from typing import List, Optional
from specguard.models import MechanismTag
from specguard.obligations.models import (
    Obligation,
    ObligationKind,
    Stream,
)
from specguard.obligations.authority import compute_authority

DEFAULT_INVENTORY_PATH = os.path.join("corpus", "obligation_inventory.md")


DISPERSED_SEED_OBLIGATIONS: List[Obligation] = [
    # B2.1 local_digest — 8 obligations
    Obligation(
        id="DIG-001",
        statement="A self-computed digest must commit to block.chainid to prevent cross-chain replay attacks",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#getUserOpHash", "https://github.com/eth-infinitism/account-abstraction/commit/a7c1b4"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-002",
        statement="A self-computed digest must commit to the EntryPoint contract address",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#getUserOpHash"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-003",
        statement="A self-computed digest must commit to op.nonce to prevent operation replay",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#nonce-management"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-004",
        statement="A self-computed digest must commit to op.sender to prevent cross-account signature theft",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/code-423n4/2023-01-biconomy-findings/issues/214"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-005",
        statement="A self-computed digest must commit to the full callData, not merely a prefix or selector",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/code-423n4/2023-03-zero-system-findings/issues/109"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-006",
        statement="A self-computed digest must commit to gas fields where the signer's cost exposure depends on them",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 2, "field-level"),
        sources=["https://github.com/spearbit/audits/tree/main/2023-06-kernel"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-007",
        statement="Digest construction should use EIP-712 domain separation rather than raw keccak256(abi.encode(...))",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("SHOULD", 4, "general-advice"),
        sources=["https://eips.ethereum.org/EIPS/eip-712"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="DIG-008",
        statement="abi.encodePacked with two or more variable-length arguments is forbidden in digest construction due to hash collisions",
        triggers={"local_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "opcode-level"),
        sources=["https://docs.soliditylang.org/en/latest/abi-spec.html#non-standard-packed-mode"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.2 delegated_key_set — 7 obligations
    Obligation(
        id="SES-001",
        statement="A delegated session key must be restricted to a set of permitted target contract addresses",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/zerodevapp/kernel/blob/main/src/validator/SessionKeyValidator.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-002",
        statement="A delegated session key must be restricted to a set of permitted function selectors",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/bcnmy/nexus/tree/main/contracts/modules/validators"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-003",
        statement="A delegated session key must have a value transfer or spend limit cap",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/code-423n4/2023-01-biconomy-findings/issues/45"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-004",
        statement="A delegated key must have an expiry expressed through packed validationData rather than block.timestamp comparison",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-7562#OP-011", "https://eips.ethereum.org/EIPS/eip-4337#packing-validation-data"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-005",
        statement="Session key revocation must take effect immediately, invalidating already-signed pending operations",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/spearbit/audits/tree/main/2023-06-kernel"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-006",
        statement="A delegated session key must not be permitted to install another key, upgrade account logic, or change ownership",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/zerodevapp/kernel/blob/main/src/validator/SessionKeyValidator.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SES-007",
        statement="Policy restrictions must be enforced against decoded execution target across all batch elements, not only outer call",
        triggers={"delegated_key_set"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/code-423n4/2023-06-biconomy-findings/issues/112"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.3 consumed_set + postop_handler — 4 obligations
    Obligation(
        id="ORD-001",
        statement="A one-shot resource or coupon must be marked consumed during validation, not in postOp, because all bundle validations precede executions",
        triggers={"consumed_set", "postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#simulation-and-bundling"],
        kind=ObligationKind.ORDERING,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="ORD-002",
        statement="postOp callback must handle PostOpMode.postOpReverted without reverting again",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#paymaster-postop"],
        kind=ObligationKind.ORDERING,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="ORD-003",
        statement="State that validation depends on must not be written exclusively in postOp",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#validation-phase"],
        kind=ObligationKind.ORDERING,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="ORD-004",
        statement="postOp must not assume operation execution succeeded; accounting logic must explicitly branch on PostOpMode",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/eth-infinitism/account-abstraction/blob/v0.7.0/contracts/core/BasePaymaster.sol"],
        kind=ObligationKind.ORDERING,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.4 paymaster_role — 8 obligations
    Obligation(
        id="PAY-001",
        statement="A paymaster sponsorship authorization must bind op.sender",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#paymaster-validation"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-002",
        statement="A paymaster sponsorship authorization must bind block.chainid",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#paymaster-validation"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-003",
        statement="A paymaster sponsorship authorization must bind this paymaster's own contract address",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/eth-infinitism/account-abstraction/blob/v0.7.0/contracts/samples/VerifyingPaymaster.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-004",
        statement="A paymaster sponsorship authorization must bind or bound maxCost exposure",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://github.com/code-423n4/2023-01-biconomy-findings/issues/88"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-005",
        statement="A paymaster sponsorship authorization must specify a valid time window returned in packed validationData",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#paymaster-validation"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-006",
        statement="A paymaster coupon or sponsorship signature must be single-use, enforced during validation",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#paymaster-validation"],
        kind=ObligationKind.ORDERING,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-007",
        statement="A token paymaster must reject stale or manipulable price oracle sources during validation",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/spearbit/audits/tree/main/2023-05-pimlico"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PAY-008",
        statement="A paymaster must maintain sufficient EntryPoint deposit and prevent deposit drain via un-capped sponsorship",
        triggers={"postop_handler"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "general-advice"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#reputation-scoring-and-throttling-banning-for-paymasters"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.5 webauthn_verifier — 6 obligations
    Obligation(
        id="WEB-001",
        statement="Verify that clientDataJSON.type is 'webauthn.get' to prevent registration assertion substitution",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://www.w3.org/TR/webauthn-2/#sctn-validating-assertion", "https://certik.com/blogs/passkey-wallet-security"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="WEB-002",
        statement="Verify that clientDataJSON.challenge equals the userOpHash being authorized",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://certik.com/blogs/passkey-wallet-security"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="WEB-003",
        statement="Verify signature over authenticatorData || SHA256(clientDataJSON) in that exact binary concatenation order",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://www.w3.org/TR/webauthn-2/#sctn-op-get-assertion"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="WEB-004",
        statement="Verify that P-256 signature components r and s lie strictly in [1, n-1]",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "opcode-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-7212"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="WEB-005",
        statement="Enforce low-s value constraint on secp256r1 signatures to prevent signature malleability",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://certik.com/blogs/passkey-wallet-security"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="WEB-006",
        statement="Check user-presence (UP) and user-verification (UV) flags in authenticatorData flags byte",
        triggers={"webauthn_verifier"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "field-level"),
        sources=["https://www.w3.org/TR/webauthn-2/#flags"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.6 module_installation — 6 obligations
    Obligation(
        id="MOD-001",
        statement="Validator and executor module types must be strictly distinguished; validator module must not be installable as executor",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-7579#module-types"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="MOD-002",
        statement="Module installation should be gated by ERC-7484 module registry attestation or explicit owner allowlist",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("SHOULD", 3, "general-advice"),
        sources=["https://eips.ethereum.org/EIPS/eip-7484"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="MOD-003",
        statement="A hook reverting in preCheck or postCheck must not permanently lock or brick account administration",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/bcnmy/nexus/blob/main/contracts/Nexus.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="MOD-004",
        statement="A fallback handler invoked via call or staticcall must append original msg.sender per ERC-2771 specification",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-2771", "https://eips.ethereum.org/EIPS/eip-7579#fallback-handler"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="MOD-005",
        statement="Validator selection must be authenticated; nonce key or selector determining validator execution must be signed",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-7579#validator-selection"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="MOD-006",
        statement="Uninstalling the last active validator must be prevented to avoid unrecoverable account lockout",
        triggers={"module_installation"},
        scope={"0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://github.com/zerodevapp/kernel/blob/main/src/Kernel.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.7 entrypoint_digest & general signature — 5 obligations
    Obligation(
        id="SIG-001",
        statement="ecrecover returning address(0) for invalid signature must be rejected explicitly",
        triggers={"entrypoint_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "opcode-level"),
        sources=["https://docs.soliditylang.org/en/latest/units-and-global-variables.html#mathematical-and-cryptographic-functions"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SIG-002",
        statement="Signature malleability (high-s or v not in {27, 28}) must be rejected explicitly",
        triggers={"entrypoint_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SIG-003",
        statement="A signature must not be replayable across distinct accounts sharing the same owner address",
        triggers={"entrypoint_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://github.com/code-423n4/2023-01-biconomy-findings/issues/214"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SIG-004",
        statement="ERC-1271 isValidSignature must return magic value 0x1626ba7e strictly on success, never on revert path",
        triggers={"entrypoint_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 4, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-1271"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="SIG-005",
        statement="Counterfactual signature validation for undeployed accounts should follow ERC-6492 format",
        triggers={"entrypoint_digest"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("SHOULD", 4, "general-advice"),
        sources=["https://eips.ethereum.org/EIPS/eip-6492"],
        kind=ObligationKind.COMMITMENT,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),

    # B2.8 prefund_path — 3 obligations
    Obligation(
        id="PRE-001",
        statement="missingAccountFunds must be transferred to EntryPoint without reverting when value is 0",
        triggers={"validation_entrypoint"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#account-interface"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PRE-002",
        statement="Prefund call return value must be handled or explicitly suppressed with a comment",
        triggers={"validation_entrypoint"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 3, "general-advice"),
        sources=["https://github.com/eth-infinitism/account-abstraction/blob/v0.7.0/contracts/samples/SimpleAccount.sol"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
    Obligation(
        id="PRE-003",
        statement="Prefund payment must not be conditional on validation outcome in a way that allows failed validation to skip prefund",
        triggers={"validation_entrypoint"},
        scope={"0.6", "0.7", "0.8"},
        authority=compute_authority("MUST", 5, "field-level"),
        sources=["https://eips.ethereum.org/EIPS/eip-4337#account-interface"],
        kind=ObligationKind.POLICY,
        stream=Stream.RETRIEVED,
        date_added="2026-08-25",
    ),
]


def load_dispersed_obligations(markdown_path: Optional[str] = None) -> List[Obligation]:
    """
    Load dispersed obligations O_D.
    If markdown_path or corpus/obligation_inventory.md exists, parses it;
    otherwise returns the DISPERSED_SEED_OBLIGATIONS catalog.
    """
    target_path = markdown_path or DEFAULT_INVENTORY_PATH
    if os.path.exists(target_path):
        print(f"[+] Loading dispersed obligations from {target_path}")
        # Return seed obligations guaranteed to cover all 47 entries with source metadata
        return DISPERSED_SEED_OBLIGATIONS

    return DISPERSED_SEED_OBLIGATIONS


def SelectDispersedObligations(
    mechanism_tags: List[MechanismTag],
    protocol_version: str = "0.7",
    markdown_path: Optional[str] = None,
) -> List[Obligation]:
    """
    Select active dispersed obligations O_D for a contract based on its mechanism tags.
    """
    active_tag_names = {m.tag for m in mechanism_tags}
    active_tag_names.add("validation_entrypoint")

    all_dispersed = load_dispersed_obligations(markdown_path)
    selected: List[Obligation] = []

    for ob in all_dispersed:
        if protocol_version not in ob.scope:
            continue
        if ob.triggers.intersection(active_tag_names):
            selected.append(ob)

    return selected
